#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("ViewPagerIndicatorQs.Resource", IsApplication=true)]

namespace ViewPagerIndicatorQs
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010000
			public const int centered = 2130771968;
			
			// aapt resource value: 0x7f01000b
			public const int clipPadding = 2130771979;
			
			// aapt resource value: 0x7f010017
			public const int fadeDelay = 2130771991;
			
			// aapt resource value: 0x7f010018
			public const int fadeLength = 2130771992;
			
			// aapt resource value: 0x7f010016
			public const int fades = 2130771990;
			
			// aapt resource value: 0x7f010004
			public const int fillColor = 2130771972;
			
			// aapt resource value: 0x7f01000c
			public const int footerColor = 2130771980;
			
			// aapt resource value: 0x7f01000f
			public const int footerIndicatorHeight = 2130771983;
			
			// aapt resource value: 0x7f01000e
			public const int footerIndicatorStyle = 2130771982;
			
			// aapt resource value: 0x7f010010
			public const int footerIndicatorUnderlinePadding = 2130771984;
			
			// aapt resource value: 0x7f01000d
			public const int footerLineHeight = 2130771981;
			
			// aapt resource value: 0x7f010011
			public const int footerPadding = 2130771985;
			
			// aapt resource value: 0x7f01000a
			public const int gapWidth = 2130771978;
			
			// aapt resource value: 0x7f010012
			public const int linePosition = 2130771986;
			
			// aapt resource value: 0x7f010009
			public const int lineWidth = 2130771977;
			
			// aapt resource value: 0x7f010005
			public const int pageColor = 2130771973;
			
			// aapt resource value: 0x7f010006
			public const int radius = 2130771974;
			
			// aapt resource value: 0x7f010013
			public const int selectedBold = 2130771987;
			
			// aapt resource value: 0x7f010001
			public const int selectedColor = 2130771969;
			
			// aapt resource value: 0x7f010007
			public const int snap = 2130771975;
			
			// aapt resource value: 0x7f010008
			public const int strokeColor = 2130771976;
			
			// aapt resource value: 0x7f010002
			public const int strokeWidth = 2130771970;
			
			// aapt resource value: 0x7f010014
			public const int titlePadding = 2130771988;
			
			// aapt resource value: 0x7f010015
			public const int topPadding = 2130771989;
			
			// aapt resource value: 0x7f010003
			public const int unselectedColor = 2130771971;
			
			// aapt resource value: 0x7f010019
			public const int vpiCirclePageIndicatorStyle = 2130771993;
			
			// aapt resource value: 0x7f01001a
			public const int vpiIconPageIndicatorStyle = 2130771994;
			
			// aapt resource value: 0x7f01001b
			public const int vpiLinePageIndicatorStyle = 2130771995;
			
			// aapt resource value: 0x7f01001d
			public const int vpiTabPageIndicatorStyle = 2130771997;
			
			// aapt resource value: 0x7f01001c
			public const int vpiTitlePageIndicatorStyle = 2130771996;
			
			// aapt resource value: 0x7f01001e
			public const int vpiUnderlinePageIndicatorStyle = 2130771998;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Boolean
		{
			
			// aapt resource value: 0x7f040000
			public const int default_circle_indicator_centered = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int default_circle_indicator_snap = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int default_line_indicator_centered = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int default_title_indicator_selected_bold = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int default_underline_indicator_fades = 2130968580;
			
			static Boolean()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Boolean()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f050000
			public const int default_circle_indicator_fill_color = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int default_circle_indicator_page_color = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int default_circle_indicator_stroke_color = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int default_line_indicator_selected_color = 2131034115;
			
			// aapt resource value: 0x7f050004
			public const int default_line_indicator_unselected_color = 2131034116;
			
			// aapt resource value: 0x7f050005
			public const int default_title_indicator_footer_color = 2131034117;
			
			// aapt resource value: 0x7f050006
			public const int default_title_indicator_selected_color = 2131034118;
			
			// aapt resource value: 0x7f050007
			public const int default_title_indicator_text_color = 2131034119;
			
			// aapt resource value: 0x7f050008
			public const int default_underline_indicator_selected_color = 2131034120;
			
			// aapt resource value: 0x7f050009
			public const int vpi__background_holo_dark = 2131034121;
			
			// aapt resource value: 0x7f05000a
			public const int vpi__background_holo_light = 2131034122;
			
			// aapt resource value: 0x7f05000b
			public const int vpi__bright_foreground_disabled_holo_dark = 2131034123;
			
			// aapt resource value: 0x7f05000c
			public const int vpi__bright_foreground_disabled_holo_light = 2131034124;
			
			// aapt resource value: 0x7f05000d
			public const int vpi__bright_foreground_holo_dark = 2131034125;
			
			// aapt resource value: 0x7f05000e
			public const int vpi__bright_foreground_holo_light = 2131034126;
			
			// aapt resource value: 0x7f05000f
			public const int vpi__bright_foreground_inverse_holo_dark = 2131034127;
			
			// aapt resource value: 0x7f050010
			public const int vpi__bright_foreground_inverse_holo_light = 2131034128;
			
			// aapt resource value: 0x7f050011
			public const int vpi__dark_theme = 2131034129;
			
			// aapt resource value: 0x7f050012
			public const int vpi__light_theme = 2131034130;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f060000
			public const int default_circle_indicator_radius = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int default_circle_indicator_stroke_width = 2131099649;
			
			// aapt resource value: 0x7f060002
			public const int default_line_indicator_gap_width = 2131099650;
			
			// aapt resource value: 0x7f060003
			public const int default_line_indicator_line_width = 2131099651;
			
			// aapt resource value: 0x7f060004
			public const int default_line_indicator_stroke_width = 2131099652;
			
			// aapt resource value: 0x7f060005
			public const int default_title_indicator_clip_padding = 2131099653;
			
			// aapt resource value: 0x7f060006
			public const int default_title_indicator_footer_indicator_height = 2131099654;
			
			// aapt resource value: 0x7f060007
			public const int default_title_indicator_footer_indicator_underline_padding = 2131099655;
			
			// aapt resource value: 0x7f060008
			public const int default_title_indicator_footer_line_height = 2131099656;
			
			// aapt resource value: 0x7f060009
			public const int default_title_indicator_footer_padding = 2131099657;
			
			// aapt resource value: 0x7f06000a
			public const int default_title_indicator_text_size = 2131099658;
			
			// aapt resource value: 0x7f06000b
			public const int default_title_indicator_title_padding = 2131099659;
			
			// aapt resource value: 0x7f06000c
			public const int default_title_indicator_top_padding = 2131099660;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int custom_tab_indicator = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int custom_tab_indicator_divider = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int custom_tab_indicator_selected = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int custom_tab_indicator_selected_focused = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int custom_tab_indicator_selected_pressed = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int custom_tab_indicator_unselected = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int custom_tab_indicator_unselected_focused = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int custom_tab_indicator_unselected_pressed = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int Icon = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int perm_group_calendar = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int perm_group_calendar_normal = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int perm_group_calendar_selected = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int perm_group_camera = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int perm_group_camera_normal = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int perm_group_camera_selected = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int perm_group_device_alarms = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int perm_group_device_alarms_normal = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int perm_group_device_alarms_selected = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int perm_group_location = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int perm_group_location_normal = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int perm_group_location_selected = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int vpi__tab_indicator = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int vpi__tab_selected_focused_holo = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int vpi__tab_selected_holo = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int vpi__tab_selected_pressed_holo = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int vpi__tab_unselected_focused_holo = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int vpi__tab_unselected_holo = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int vpi__tab_unselected_pressed_holo = 2130837531;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f0b0005
			public const int SampleCirclesDefault = 2131427333;
			
			// aapt resource value: 0x7f0b0006
			public const int SampleCirclesInitialPage = 2131427334;
			
			// aapt resource value: 0x7f0b0007
			public const int SampleCirclesSnap = 2131427335;
			
			// aapt resource value: 0x7f0b0008
			public const int SampleCirclesStyledLayout = 2131427336;
			
			// aapt resource value: 0x7f0b0009
			public const int SampleCirclesStyledMethods = 2131427337;
			
			// aapt resource value: 0x7f0b000a
			public const int SampleCirclesStyledTheme = 2131427338;
			
			// aapt resource value: 0x7f0b000b
			public const int SampleCirclesWithListener = 2131427339;
			
			// aapt resource value: 0x7f0b000c
			public const int SampleIconsDefault = 2131427340;
			
			// aapt resource value: 0x7f0b000d
			public const int SampleLinesDefault = 2131427341;
			
			// aapt resource value: 0x7f0b000e
			public const int SampleLinesStyledLayout = 2131427342;
			
			// aapt resource value: 0x7f0b000f
			public const int SampleLinesStyledMethods = 2131427343;
			
			// aapt resource value: 0x7f0b0010
			public const int SampleLinesStyledTheme = 2131427344;
			
			// aapt resource value: 0x7f0b0011
			public const int SampleTabsDefault = 2131427345;
			
			// aapt resource value: 0x7f0b0012
			public const int SampleTabsStyled = 2131427346;
			
			// aapt resource value: 0x7f0b0013
			public const int SampleTabsWithIcons = 2131427347;
			
			// aapt resource value: 0x7f0b0014
			public const int SampleTitlesBottom = 2131427348;
			
			// aapt resource value: 0x7f0b0015
			public const int SampleTitlesCenterClickListener = 2131427349;
			
			// aapt resource value: 0x7f0b0016
			public const int SampleTitlesDefault = 2131427350;
			
			// aapt resource value: 0x7f0b0017
			public const int SampleTitlesInitialPage = 2131427351;
			
			// aapt resource value: 0x7f0b0018
			public const int SampleTitlesStyledLayout = 2131427352;
			
			// aapt resource value: 0x7f0b0019
			public const int SampleTitlesStyledMethods = 2131427353;
			
			// aapt resource value: 0x7f0b001a
			public const int SampleTitlesStyledTheme = 2131427354;
			
			// aapt resource value: 0x7f0b001b
			public const int SampleTitlesTriangle = 2131427355;
			
			// aapt resource value: 0x7f0b001c
			public const int SampleTitlesWithListener = 2131427356;
			
			// aapt resource value: 0x7f0b001d
			public const int SampleUnderlinesDefault = 2131427357;
			
			// aapt resource value: 0x7f0b001e
			public const int SampleUnderlinesNoFade = 2131427358;
			
			// aapt resource value: 0x7f0b001f
			public const int SampleUnderlinesStyledLayout = 2131427359;
			
			// aapt resource value: 0x7f0b0020
			public const int SampleUnderlinesStyledMethods = 2131427360;
			
			// aapt resource value: 0x7f0b0021
			public const int SampleUnderlinesStyledTheme = 2131427361;
			
			// aapt resource value: 0x7f0b0025
			public const int add_page = 2131427365;
			
			// aapt resource value: 0x7f0b0003
			public const int bottom = 2131427331;
			
			// aapt resource value: 0x7f0b0023
			public const int indicator = 2131427363;
			
			// aapt resource value: 0x7f0b0000
			public const int none = 2131427328;
			
			// aapt resource value: 0x7f0b0022
			public const int pager = 2131427362;
			
			// aapt resource value: 0x7f0b0024
			public const int random = 2131427364;
			
			// aapt resource value: 0x7f0b0026
			public const int remove_page = 2131427366;
			
			// aapt resource value: 0x7f0b0004
			public const int top = 2131427332;
			
			// aapt resource value: 0x7f0b0001
			public const int triangle = 2131427329;
			
			// aapt resource value: 0x7f0b0002
			public const int underline = 2131427330;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Integer
		{
			
			// aapt resource value: 0x7f070000
			public const int default_circle_indicator_orientation = 2131165184;
			
			// aapt resource value: 0x7f070001
			public const int default_title_indicator_footer_indicator_style = 2131165185;
			
			// aapt resource value: 0x7f070002
			public const int default_title_indicator_line_position = 2131165186;
			
			// aapt resource value: 0x7f070003
			public const int default_underline_indicator_fade_delay = 2131165187;
			
			// aapt resource value: 0x7f070004
			public const int default_underline_indicator_fade_length = 2131165188;
			
			static Integer()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Integer()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int simple_circles = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int simple_circles_vertical = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int simple_icons = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int simple_lines = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int simple_tabs = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int simple_titles = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int simple_titles_bottom = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int simple_underlines = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int themed_circles = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int themed_lines = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int themed_titles = 2130903051;
			
			// aapt resource value: 0x7f03000c
			public const int themed_underlines = 2130903052;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f0a0000
			public const int menu = 2131361792;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f090001
			public const int ApplicationName = 2131296257;
			
			// aapt resource value: 0x7f090000
			public const int Hello = 2131296256;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f080008
			public const int CustomCirclePageIndicator = 2131230728;
			
			// aapt resource value: 0x7f080007
			public const int CustomLinePageIndicator = 2131230727;
			
			// aapt resource value: 0x7f080009
			public const int CustomTabPageIndicator = 2131230729;
			
			// aapt resource value: 0x7f08000a
			public const int CustomTabPageIndicator_Text = 2131230730;
			
			// aapt resource value: 0x7f080006
			public const int CustomTitlePageIndicator = 2131230726;
			
			// aapt resource value: 0x7f08000b
			public const int CustomUnderlinePageIndicator = 2131230731;
			
			// aapt resource value: 0x7f080005
			public const int StyledIndicators = 2131230725;
			
			// aapt resource value: 0x7f080000
			public const int TextAppearance_TabPageIndicator = 2131230720;
			
			// aapt resource value: 0x7f080001
			public const int Theme_PageIndicatorDefaults = 2131230721;
			
			// aapt resource value: 0x7f080002
			public const int Widget = 2131230722;
			
			// aapt resource value: 0x7f080003
			public const int Widget_IconPageIndicator = 2131230723;
			
			// aapt resource value: 0x7f080004
			public const int Widget_TabPageIndicator = 2131230724;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] CirclePageIndicator = new int[] {
					16842948,
					16842964,
					2130771968,
					2130771970,
					2130771972,
					2130771973,
					2130771974,
					2130771975,
					2130771976};
			
			// aapt resource value: 1
			public const int CirclePageIndicator_android_background = 1;
			
			// aapt resource value: 0
			public const int CirclePageIndicator_android_orientation = 0;
			
			// aapt resource value: 2
			public const int CirclePageIndicator_centered = 2;
			
			// aapt resource value: 4
			public const int CirclePageIndicator_fillColor = 4;
			
			// aapt resource value: 5
			public const int CirclePageIndicator_pageColor = 5;
			
			// aapt resource value: 6
			public const int CirclePageIndicator_radius = 6;
			
			// aapt resource value: 7
			public const int CirclePageIndicator_snap = 7;
			
			// aapt resource value: 8
			public const int CirclePageIndicator_strokeColor = 8;
			
			// aapt resource value: 3
			public const int CirclePageIndicator_strokeWidth = 3;
			
			public static int[] LinePageIndicator = new int[] {
					16842964,
					2130771968,
					2130771969,
					2130771970,
					2130771971,
					2130771977,
					2130771978};
			
			// aapt resource value: 0
			public const int LinePageIndicator_android_background = 0;
			
			// aapt resource value: 1
			public const int LinePageIndicator_centered = 1;
			
			// aapt resource value: 6
			public const int LinePageIndicator_gapWidth = 6;
			
			// aapt resource value: 5
			public const int LinePageIndicator_lineWidth = 5;
			
			// aapt resource value: 2
			public const int LinePageIndicator_selectedColor = 2;
			
			// aapt resource value: 3
			public const int LinePageIndicator_strokeWidth = 3;
			
			// aapt resource value: 4
			public const int LinePageIndicator_unselectedColor = 4;
			
			public static int[] TitlePageIndicator = new int[] {
					16842901,
					16842904,
					16842964,
					2130771969,
					2130771979,
					2130771980,
					2130771981,
					2130771982,
					2130771983,
					2130771984,
					2130771985,
					2130771986,
					2130771987,
					2130771988,
					2130771989};
			
			// aapt resource value: 2
			public const int TitlePageIndicator_android_background = 2;
			
			// aapt resource value: 1
			public const int TitlePageIndicator_android_textColor = 1;
			
			// aapt resource value: 0
			public const int TitlePageIndicator_android_textSize = 0;
			
			// aapt resource value: 4
			public const int TitlePageIndicator_clipPadding = 4;
			
			// aapt resource value: 5
			public const int TitlePageIndicator_footerColor = 5;
			
			// aapt resource value: 8
			public const int TitlePageIndicator_footerIndicatorHeight = 8;
			
			// aapt resource value: 7
			public const int TitlePageIndicator_footerIndicatorStyle = 7;
			
			// aapt resource value: 9
			public const int TitlePageIndicator_footerIndicatorUnderlinePadding = 9;
			
			// aapt resource value: 6
			public const int TitlePageIndicator_footerLineHeight = 6;
			
			// aapt resource value: 10
			public const int TitlePageIndicator_footerPadding = 10;
			
			// aapt resource value: 11
			public const int TitlePageIndicator_linePosition = 11;
			
			// aapt resource value: 12
			public const int TitlePageIndicator_selectedBold = 12;
			
			// aapt resource value: 3
			public const int TitlePageIndicator_selectedColor = 3;
			
			// aapt resource value: 13
			public const int TitlePageIndicator_titlePadding = 13;
			
			// aapt resource value: 14
			public const int TitlePageIndicator_topPadding = 14;
			
			public static int[] UnderlinePageIndicator = new int[] {
					16842964,
					2130771969,
					2130771990,
					2130771991,
					2130771992};
			
			// aapt resource value: 0
			public const int UnderlinePageIndicator_android_background = 0;
			
			// aapt resource value: 3
			public const int UnderlinePageIndicator_fadeDelay = 3;
			
			// aapt resource value: 4
			public const int UnderlinePageIndicator_fadeLength = 4;
			
			// aapt resource value: 2
			public const int UnderlinePageIndicator_fades = 2;
			
			// aapt resource value: 1
			public const int UnderlinePageIndicator_selectedColor = 1;
			
			public static int[] ViewPagerIndicator = new int[] {
					2130771993,
					2130771994,
					2130771995,
					2130771996,
					2130771997,
					2130771998};
			
			// aapt resource value: 0
			public const int ViewPagerIndicator_vpiCirclePageIndicatorStyle = 0;
			
			// aapt resource value: 1
			public const int ViewPagerIndicator_vpiIconPageIndicatorStyle = 1;
			
			// aapt resource value: 2
			public const int ViewPagerIndicator_vpiLinePageIndicatorStyle = 2;
			
			// aapt resource value: 4
			public const int ViewPagerIndicator_vpiTabPageIndicatorStyle = 4;
			
			// aapt resource value: 3
			public const int ViewPagerIndicator_vpiTitlePageIndicatorStyle = 3;
			
			// aapt resource value: 5
			public const int ViewPagerIndicator_vpiUnderlinePageIndicatorStyle = 5;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
